version: "3.8"
services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d:ro
    ports:
      - "3307:3306"
  nginx:
    image: nginx
    restart: always
    volumes:
      - ./nginx/src:/etc/nginx/html/
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8081:80"
    links:
      - db
  apache:
    build: ./apache-php
    restart: always
    volumes:
      - ./apache-php/src:/var/www/html/
      - ./apache-php/000-default.conf:/etc/apache2/sites-available/000-default.conf
      - ./apache-php/php.ini:/usr/local/etc/php/conf.d/custom.ini
    ports:
      - "8082:80"
    links:
      - db
      - nginx
  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"